### PR TITLE
Fix invalid json (typo)

### PR DESCRIPTION
**Pull request by martinssipenko**

### CODE REVIEW

**Review by piotrooo — APPROVED** [review]
It's ok. Should be merged ASAP.

**Comment by NoelDavies** [comment]
I'm not sure how this got in there, thanks!

**Comment by martinssipenko** [comment]
@NoelDavies this is a result of the lack of CI (#9) .

**Comment by NoelDavies** [comment]
Couldn't agree more mate.

**Comment by NoelDavies** [comment]
Released in `v1.0.2`

**Pull request merged**
