### PR TITLE
Introduce Continuous Integration

### LINKED ISSUE #9: CI missing after forking
It seems that CI is missing after fork was made. I'd be happy to contribute to add CI pipeline for this project. I'd like to propose moving to CircleCI instead of using TravisCI, in my experience CircleCI is more robust and has more features, but I'm happy to contribute either way.

### PR DESCRIPTION
**Pull request by martinssipenko**
Continuous Integration pipeline. Right now it's executed on PHP 7.3 and there are two builds - one with latest requires and one with lowest requires, lowest is required to make sure things work on minimum requirements.

Resolves #9 #11

### CODE REVIEW

**Review by piotrooo — CHANGES_REQUESTED** [review]
I think you should squash similar commits with appropriate commit message.

**Comment by martinssipenko** [comment]
@piotrooo They can be squashed on merge, guthub allows to do that.

**Comment by piotrooo** [comment]
You are responsible for your commits. You exactly know what you did. So who can better squash your commits than you? :)

**Comment by martinssipenko** [comment]
GitHub can do it as good as I can (screenshot from other project):
image

**Comment by piotrooo** [comment]
ping @NoelDavies lets merge PRs :)

**Pull request merged**
