### PR TITLE
Add code style check into CI pipeline

### LINKED ISSUE #18: Use PHP-CS-Fixer
There should be some code style standards. https://github.com/FriendsOfPHP/PHP-CS-Fixer should be helpfull, in CI integration and normal development.

### PR DESCRIPTION
**Pull request by martinssipenko**
Adds checking of coding standard (PSR-12) as part of CI pipeline.

Resolves #18

### CODE REVIEW

**Review by piotrooo — CHANGES_REQUESTED** [review]
I think you should squash similar commits with appropriate commit message.

This PR also closes #11

**Comment by martinssipenko** [comment]
I’ll rebase this if #20 is merged first. Or if this gets merged as squash, then #20 can be closed.

**Review by NoelDavies — APPROVED** [review]
Looks good!

**Comment by NoelDavies** [comment]
I Merged in #20 - You can rebase this and I can merge this in

**Comment by martinssipenko** [comment]
@NoelDavies done

**Comment by martinssipenko** [comment]
Ugh, the test are failing because #17 was merged without working CI, I'll try to fix it.

**Comment by NoelDavies** [comment]
Ah sorry mate. I'm just going through them as I can.

**Comment by martinssipenko** [comment]
@NoelDavies can you take a look at #22 and merge it?

**Comment by martinssipenko** [comment]
I'm sorry for confusion, tests are failing due to [bug in guzzle](https://github.com/guzzle/guzzle/pull/1686) in version below 6.3. I'm updating minimum guzzle version which fixes the issue.

**Comment by martinssipenko** [comment]
@NoelDavies it's now green, after merging this master branch builds will also become green.

**Comment by NoelDavies** [comment]
This would have to be a major version change as the dependency for guzzle changes.

**Comment by martinssipenko** [comment]
@NoelDavies It's a minor version change for guzzle which is backwards compatible, should also be a minor version for this package. Either way when using guzzle < 6.3 with current master it will not work, you will get the same error that was caught in tests.

**Comment by martinssipenko** [comment]
@NoelDavies can we merge this to get CI green again?

**Comment by NoelDavies** [comment]
Apologies I thought I'd merged this

**Pull request merged**
